### PR TITLE
Create CLA.md

### PR DESCRIPTION
**Pull request by lesserwhirls**
Add a Contributor License Agreement to Rosetta. Fixes Unidata/rosetta#51

### CODE REVIEW

**Comment by lesserwhirls** [comment]
@dopplershift @ethanrd - comments? This is a bit different that MetPy, in that UCAR/Unidata and Rosetta are called out in different parts of the text. The CLA itself is all UCAR/Unidata and only mentions the rosetta project in the clahub link.

**Comment by lesserwhirls** [comment]
My hope is that when we use this in another project, we can simply replace references to rosetta to the appropriate project, and update the clahub link.

**Comment by dopplershift** [comment]
Oh, I had one that said UCAR/Unidata. My bad.

**Comment by dopplershift** [comment]
Well, I had the actual CLA anyway--that was probably the short part of this anyways.

**Pull request closed without merging**
